const assert = require('node:assert/strict');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1080}, deviceScaleFactor:1});
  const errors=[];page.on('pageerror', error=>errors.push(error.message));
  await page.goto(process.env.DEMO_URL || 'http://127.0.0.1:3102');
  await page.getByRole('heading',{name:'Start an investigation'}).waitFor();
  await page.getByText('Connect reputation agents').click();
  await page.locator('#vt-key').fill('temporary-browser-only-key');
  assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
  await page.reload();
  assert.equal(await page.locator('#vt-key').inputValue(),'');
  await page.getByRole('button',{name:'Suspicious pattern'}).click();
  await page.locator('#risk').filter({hasText:'high concern'}).waitFor();
  await page.locator('#unified-title').filter({hasText:'Likely malicious'}).waitFor();
  assert.equal(await page.locator('#stages li').count(),5);
  assert.ok(Number(await page.locator('#score').textContent())>=50);
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'docs/demo-desktop.png',fullPage:true});
  await page.locator('#decision').selectOption('suspicious');
  await page.locator('#note').fill('Demo review: account language and an unrelated hostname warrant independent verification.');
  await page.getByRole('button',{name:'Save review'}).click();
  await page.locator('#review-result').filter({hasText:'Suspicious'}).waitFor();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export case'}).click();
  const download=await downloadPromise;
  assert.match(download.suggestedFilename(),/^phishscope-.*\.json$/);
  await page.reload();
  await page.locator('#history-body tr').first().getByRole('button').click();
  await page.locator('#review-result').filter({hasText:'Suspicious'}).waitFor();
  await page.locator('#url').fill('http://127.0.0.1');
  await page.getByRole('button',{name:'Analyze URL'}).click();
  await page.locator('#error').filter({hasText:'Private'}).waitFor();
  await page.getByRole('button',{name:'Everyday URL'}).click();
  await page.locator('#risk').filter({hasText:'low concern'}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>window.scrollTo(0,0));
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile layout must not overflow');
  await page.screenshot({path:'docs/demo-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('Browser checks passed: high/low analysis, 5 stages, review persistence, JSON export, private URL error, mobile layout, no JS errors.');
})().catch(error=>{console.error(error);process.exit(1);});
